version: "3"

# Sensitive variables are loaded from the .env file, e.g. AWS_ECR_URL
dotenv: [".env"]

vars:
  # Use the same postgres instance for atlas and local development, to ensure atlas also has the same extensions
  ATLAS_DEV_DB_URL: "postgres://postgres:postgres@localhost:5432/atlasdev"
  LOCAL_DB_URL: "postgres://postgres:postgres@localhost:5432/koogodb?sslmode=disable"
  MIGRATION_DIR: "file://internal/repo/postgres/migrations"
  AWS_ECR_URL: "$AWS_ECR_URL"
  AWS_ECR_REPO: "kootic/koogo-snapshot"
  AWS_ECR_OTEL_REPO: "kootic/otel-collector"

tasks:
  lint:
    cmds:
      - go mod tidy
      - golangci-lint run ./... --fix

  test:
    cmds:
      - RUN_INTEGRATION_TESTS=true go test ./...

  test:coverage:
    cmds:
      - mkdir -p coverage
      - RUN_INTEGRATION_TESTS=true go test -coverprofile=coverage/coverage.out -covermode=atomic -coverpkg=./... ./...
      - go tool cover -func=coverage/coverage.out | tail -1
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html

  generate:
    cmds:
      - swag fmt
      - swag init -g cmd/koogo/main.go --parseDependency --parseInternal --output swagger
      - go generate ./...

  docker:build:
    cmds:
      - docker build -f deployment/koogo/Dockerfile -t {{.AWS_ECR_REPO}} .

  docker:push:
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{.AWS_ECR_URL}}
      - docker tag {{.AWS_ECR_REPO}}:latest {{.AWS_ECR_URL}}/{{.AWS_ECR_REPO}}:latest
      - docker push {{.AWS_ECR_URL}}/{{.AWS_ECR_REPO}}:latest

  docker:otel:build:
    cmds:
      - docker build -f deployment/otel-collector/Dockerfile -t {{.AWS_ECR_OTEL_REPO}} .

  docker:otel:push:
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{.AWS_ECR_URL}}
      - docker tag {{.AWS_ECR_OTEL_REPO}}:latest {{.AWS_ECR_URL}}/{{.AWS_ECR_OTEL_REPO}}:latest
      - docker push {{.AWS_ECR_URL}}/{{.AWS_ECR_OTEL_REPO}}:latest

  atlas:status:
    cmds:
      - atlas --env bun
        migrate status
        --dir {{.MIGRATION_DIR}}
        --url {{.LOCAL_DB_URL}}

  atlas:hash:
    cmds:
      - atlas --env bun
        migrate hash
        --dir {{.MIGRATION_DIR}}

  atlas:diff:
    requires:
      vars: [name]
    cmds:
      - atlas --env bun
        migrate diff {{.name}}
        --dir {{.MIGRATION_DIR}}

  atlas:apply:
    cmds:
      - atlas --env bun
        migrate apply
        --dir {{.MIGRATION_DIR}}
        --url {{.LOCAL_DB_URL}}

  atlas:manual:
    requires:
      vars: [name]
    cmds:
      - atlas --env bun
        migrate new {{.name}}
        --dir {{.MIGRATION_DIR}}
