version: "3"

# Sensitive variables are loaded from the .env file, e.g. AWS_ECR_URL
dotenv: [".env"]

vars:
  # Use the same postgres instance for atlas and local development, to ensure atlas also has the same extensions
  ATLAS_DEV_DB_URL: "postgres://postgres:postgres@localhost:5432/atlasdev"
  LOCAL_DB_URL: "postgres://postgres:postgres@localhost:5432/koogo"
  MIGRATION_DIR: "file://internal/repository/dbrepo/migrations"
  SQL_SCHEMA_FILE: "file://internal/repository/dbrepo/sqlschema/main.sql"
  AWS_ECR_URL: "$AWS_ECR_URL"
  AWS_ECR_REPO: "kootic/koogo-snapshot"
  AWS_ECR_OTEL_REPO: "kootic/otel-collector"

tasks:
  lint:
    cmds:
      - go mod tidy
      - golangci-lint run ./... --fix

  test:
    cmds:
      - go test ./...

  generate:
    cmds:
      - swag fmt
      - swag init -g cmd/koogo/main.go --parseDependency --parseInternal --output swagger
      - go generate ./...

  docker:build:
    cmds:
      - docker build -f deployment/koogo/Dockerfile -t {{.AWS_ECR_REPO}} .

  docker:push:
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{.AWS_ECR_URL}}
      - docker tag {{.AWS_ECR_REPO}}:latest {{.AWS_ECR_URL}}/{{.AWS_ECR_REPO}}:latest
      - docker push {{.AWS_ECR_URL}}/{{.AWS_ECR_REPO}}:latest

  docker:otel:build:
    cmds:
      - docker build -f deployment/otel-collector/Dockerfile -t {{.AWS_ECR_OTEL_REPO}} .

  docker:otel:push:
    cmds:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin {{.AWS_ECR_URL}}
      - docker tag {{.AWS_ECR_OTEL_REPO}}:latest {{.AWS_ECR_URL}}/{{.AWS_ECR_OTEL_REPO}}:latest
      - docker push {{.AWS_ECR_URL}}/{{.AWS_ECR_OTEL_REPO}}:latest

  atlas:status:
    cmds:
      - atlas status
        --dir {{.MIGRATION_DIR}}
        --url {{.LOCAL_DB_URL}}

  atlas:hash:
    cmds:
      - atlas migrate hash
        --dir {{.MIGRATION_DIR}}

  atlas:diff:
    requires:
      vars: [name]
    cmds:
      - atlas migrate diff {{.name}}
        --dir {{.MIGRATION_DIR}}
        --to {{.SQL_SCHEMA_FILE}}
        --dev-url {{.ATLAS_DEV_DB_URL}}

  atlas:apply:
    cmds:
      - atlas migrate apply
        --dir {{.MIGRATION_DIR}}
        --url {{.LOCAL_DB_URL}}

  atlas:manual:
    requires:
      vars: [name]
    cmds:
      - atlas migrate new {{.name}}
        --dir {{.MIGRATION_DIR}}
