name: Build

run-name: "📦 Build #${{ github.run_number }}"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  build:
    name: Build
    runs-on: ubuntu-latest
